// 상품정보
const info = [
    {
        title: '캐시미어 코트 유로컬렉션 22FW 쉬어드 리얼밍크 케이프 자켓',
        subtitle: '유로컬렉션',
        price: 2000000,
        buy_price: 1850000,
        discount: `5%`,
        size: ['80', '85', '90', '95'],
        color: 'black',
        sex: 'woman',
        info_imgAr: ['../category/image/product_0/detail.jpg'],
        thum_imgAr: [
            '../category/image/product_0/0.jpg',
            '../category/image/product_0/1.jpg',
            '../category/image/product_0/2.jpg',
            '../category/image/product_0/3.jpg',
            '../category/image/product_0/4.jpg',
            '../category/image/product_0/5.jpg',
        ],
    },
    {
        title: '[PEUTEREY] 페트레이 [TAKAN VEST] 타칸베스트 WHITE - PRWVT001E0S',
        subtitle: 'PEUTEREY(페트레이) 공식수입원',
        price: 890000,
        buy_price: 801000,
        discount: `10%`,
        size: ['90', '95', '100', '105'],
        color: 'white',
        sex: 'woman',
        info_imgAr: [
            '../category/image/product_1/detail0.png',
            '../category/image/product_1/detail1.png',
            '../category/image/product_1/detail2.png',
        ],
        thum_imgAr: [
            '../category/image/product_1/0.jpg',
            '../category/image/product_1/1.jpg',
            '../category/image/product_1/2.jpg',
            '../category/image/product_1/3.jpg',
            '../category/image/product_1/4.jpg',
        ],
    },
    {
        title: '[Women][PS23][Perfect Moment] 크롭 구스다운 패딩 오렌지 (50496320821)',
        subtitle: 'BOSS (휴고보스 공식브랜드)',
        price: 1280000,
        buy_price: 1203200,
        discount: `6%`,
        size: ['80', '85', '90', '95'],
        color: 'orange',
        sex: 'woman',
        info_imgAr: [''],
        thum_imgAr: ['../category/image/product_2/0.jpg', '../category/image/product_2/1.jpg'],
    },
    {
        title: '[버버리(BURBERRY)]롱 켄징턴 헤리티지 트렌치코트',
        subtitle: '버버리(BURBERRY)',
        price: 3390000,
        buy_price: 3390000,
        discount: `0%`,
        size: ['80', '85', '90', '95'],
        color: ' burlywood',
        sex: 'woman',
        info_imgAr: [''],
        thum_imgAr: ['../category/image/product_3/0.jpg', '../category/image/product_3/1.jpg'],
    },
    {
        title: '몽클레어 (MONCLER) (선물포장)전사이즈 23SS/FW 몽클레어 란스 여성 경량패딩 블랙 LANS I10931A',
        subtitle: '몽클레어 (MONCLER) ',
        price: 1760000,
        buy_price: 1347456,
        discount: `23%`,
        size: ['80', '85', '90', '95'],
        color: 'black',
        sex: 'woman',
        info_imgAr: [''],
        thum_imgAr: ['../category/image/product_4/0.jpg', '../category/image/product_4/1.jpg'],
    },
    {
        title: '코치(COACH) 코치 여성용 솔리드 미디 트렌치코트 레드 C8771 RUBY',
        subtitle: '코치(COACH)',
        price: 429000,
        buy_price: 391248,
        discount: `8%`,
        size: ['80', '85', '90', '95'],
        color: 'red',
        sex: 'woman',
        info_imgAr: [''],
        thum_imgAr: ['../category/image/product_5/0.jpg', '../category/image/product_5/1.jpg'],
    },
    {
        title: '몽클레어 (MONCLER) 몽클레어 바람막이 히엔구 여성 레인코트 자켓 23SS',
        subtitle: '몽클레어 (MONCLER)',
        price: 1580200,
        buy_price: 1477210,
        discount: `6%`,
        size: ['80', '85', '90', '95'],
        color: 'green',
        sex: 'woman',
        info_imgAr: [''],
        thum_imgAr: ['../category/image/product_6/0.jpg', '../category/image/product_6/1.jpg'],
    },
    {
        title: '노비스 22FW 여성 메리데스 패딩 스틸그레이 MERIDETH STEEL GREY 5718513555575909 26711170',
        subtitle: '노비스 22FW',
        price: 1614600,
        buy_price: 1235815,
        discount: `23%`,
        size: ['80', '85', '90', '95'],
        color: 'gray',
        sex: 'woman',
        info_imgAr: [''],
        thum_imgAr: ['../category/image/product_7/0.jpg', '../category/image/product_7/1.jpg'],
    },
];

export default info;
