// 상품정보
const info = [
    {
        title: '캐시미어 코트 유로컬렉션 22FW 쉬어드 리얼밍크 케이프 자켓',
        subtitle: '유로컬렉션',
        price: 2000000,
        buy_price: 1850000,
        discount: `5%`,
        size: ['80', '85', '90', '95'],
        color: 'black',
        sex: 'woman',
        info_imgAr: ['../category/image/product_0/detail.jpg'],
        thum_imgAr: [
            '../category/image/product_0/0.jpg',
            '../category/image/product_0/1.jpg',
            '../category/image/product_0/2.jpg',
            '../category/image/product_0/3.jpg',
            '../category/image/product_0/4.jpg',
            '../category/image/product_0/5.jpg',
        ],
    },
    {
        title: '[PEUTEREY] 페트레이 [TAKAN VEST] 타칸베스트 WHITE - PRWVT001E0S',
        subtitle: 'PEUTEREY(페트레이) 공식수입원',
        price: 890000,
        buy_price: 801000,
        discount: `10%`,
        size: ['90', '95', '100', '105'],
        color: 'white',
        sex: 'woman',
        info_imgAr: ['../category/image/product_1/detail0.jpg'],
        thum_imgAr: [
            '../category/image/product_1/0.jpg',
            '../category/image/product_1/1.jpg',
            '../category/image/product_1/2.jpg',
            '../category/image/product_1/3.jpg',
            '../category/image/product_1/4.jpg',
            '../category/image/product_1/5.jpg',
        ],
    },
    {
        title: '[Women][PS23][Perfect Moment] 크롭 구스다운 패딩 오렌지 (50496320821)',
        subtitle: 'BOSS (휴고보스 공식브랜드)',
        price: 1280000,
        buy_price: 1203200,
        discount: `6%`,
        size: ['80', '85', '90', '95'],
        color: 'orange',
        sex: 'woman',
        info_imgAr: [''],
        thum_imgAr: ['../category/image/product_2/0.jpg', '../category/image/product_2/1.jpg'],
    },
];

export default info;
